

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "ChatPage.xaml.h"




void ::VapoRT::ChatPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///ChatPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///ChatPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the CollectionViewSource named 'itemsViewSource'
    itemsViewSource = safe_cast<::Windows::UI::Xaml::Data::CollectionViewSource^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemsViewSource"));
    // Get the ColumnDefinition named 'primaryColumn'
    primaryColumn = safe_cast<::Windows::UI::Xaml::Controls::ColumnDefinition^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"primaryColumn"));
    // Get the Grid named 'titlePanel'
    titlePanel = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"titlePanel"));
    // Get the ListView named 'ItemListView'
    ItemListView = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ItemListView"));
    // Get the ScrollViewer named 'itemDetail'
    itemDetail = safe_cast<::Windows::UI::Xaml::Controls::ScrollViewer^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemDetail"));
    // Get the ItemsControl named 'ConversationListView'
    ConversationListView = safe_cast<::Windows::UI::Xaml::Controls::ItemsControl^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ConversationListView"));
    // Get the TextBox named 'MessageComposeBox'
    MessageComposeBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"MessageComposeBox"));
    // Get the Grid named 'itemDetailGrid'
    itemDetailGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemDetailGrid"));
    // Get the StackPanel named 'itemDetailTitlePanel'
    itemDetailTitlePanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemDetailTitlePanel"));
    // Get the TextBlock named 'itemTitle'
    itemTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemTitle"));
    // Get the TextBlock named 'itemSubtitle'
    itemSubtitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"itemSubtitle"));
    // Get the Button named 'backButton'
    backButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"backButton"));
    // Get the TextBlock named 'pageTitle'
    pageTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pageTitle"));
    // Get the VisualStateGroup named 'ApplicationViewStates'
    ApplicationViewStates = safe_cast<::Windows::UI::Xaml::VisualStateGroup^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ApplicationViewStates"));
    // Get the VisualState named 'FullScreenLandscapeOrWide'
    FullScreenLandscapeOrWide = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FullScreenLandscapeOrWide"));
    // Get the VisualState named 'FilledOrNarrow'
    FilledOrNarrow = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FilledOrNarrow"));
    // Get the VisualState named 'FullScreenPortrait'
    FullScreenPortrait = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FullScreenPortrait"));
    // Get the VisualState named 'FullScreenPortrait_Detail'
    FullScreenPortrait_Detail = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FullScreenPortrait_Detail"));
    // Get the VisualState named 'Snapped'
    Snapped = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Snapped"));
    // Get the VisualState named 'Snapped_Detail'
    Snapped_Detail = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Snapped_Detail"));
}

void ::VapoRT::ChatPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->Loaded +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VapoRT::ChatPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ChatPage::chatPageLoaded);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::FrameworkElement^>(target))->Loaded +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VapoRT::ChatPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ChatPage::ConversationListView_Loaded_1);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VapoRT::ChatPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ChatPage::GoBack);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

